### ISSUE TITLE
Use resolveParameter for  params in <valueAssessment>

### ISSUE THREAD

**Issue by alanlivio** [TeleMidia/ginga#105]
This was reported by @andrelbd1 .

Today resolveParameter is called to resolve params only for set, selection, duration and delay (see lines below).

lib/Parser.cpp:2691:                    act.value = st->resolveParameter (
lib/Parser.cpp:2705:                    act.value = st->resolveParameter (
lib/Parser.cpp:2719:              act.duration = st->resolveParameter (
lib/Parser.cpp:2722:              act.delay = st->resolveParameter (role->delay, &bind->params,

The resolveParameter should also be called when a param is used in a valueAssessment (see code bellow which not work today).
I think this issue should be implemented in pushAttributeAssessment function.

```
<causalConnector id="onBeginVarStart">
  <compoundCondition operator="and">
   <connectorParam name="cmpVar">
    <simpleCondition role="onBegin"/>
    <assessmentStatement comparator="eq">
      <attributeAssessment role="var" />
      <valueAssessment value="$cmpVar"/>
    </assessmentStatement>
  </compoundCondition>
  <simpleAction role="start"/>
</causalConnector>
```

**Comment by andrelbd1** [comment]
<link xconnector="conn#onBeginSet">
        <bind component="grid" role="onBegin"/>
        <bind component="noSettingsRefer1" interface="service.currentFocus" role="set">
          <bindParam name="val" value="0"/>
        </bind>
        <bind component="noSettingsRefer1" interface="_pos0" role="set">
          <bindParam name="val" value="empty"/>
        </bind>
        <bind component="noSettingsRefer1" interface="_pos1" role="set">
          <bindParam name="val" value="empty"/>
        </bind>
        <bind component="noSettingsRefer1" interface="_pos2" role="set">
          <bindParam name="val" value="empty"/>
        </bind>
        <bind component="noSettingsRefer1" interface="_pos3" role="set">
          <bindParam name="val" value="empty"/>
        </bind>
        <bind component="noSettingsRefer1" interface="_pos4" role="set">
          <bindParam name="val" value="empty"/>
        </bind>
        <bind component="noSettingsRefer1" interface="_pos5" role="set">
          <bindParam name="val" value="empty"/>
        </bind>
        <bind component="noSettingsRefer1" interface="_pos6" role="set">
          <bindParam name="val" value="empty"/>
        </bind>
        <bind component="noSettingsRefer1" interface="_pos7" role="set">
          <bindParam name="val" value="empty"/>
        </bind>
        <bind component="noSettingsRefer1" interface="_pos8" role="set">
          <bindParam name="val" value="empty"/>
        </bind>
        <bind component="noSettingsRefer1" interface="turn" role="set">
          <bindParam name="val" value="x"/>
        </bind>
      </link>

**Comment by alanlivio** [comment]
@andrelbd1 I thinks this Link problema is not related to this issue about resolveParameter for params in <valueAssessment>.
May be it can be related to #94.

**Comment by robertogerson** [comment]
Any news about this issue?  Can we close it?

**Comment by andrelbd1** [comment]
I'm still working that. Parser is the reason of this problem.

**Comment by alanlivio** [comment]
This issue is on the release because @andrelbd1  reported that it is required by the "jogo da velha" application.

**Comment by andrelbd1** [comment]
Finally done!
