### ISSUE TITLE
gingagui failing in windows after deploy

### ISSUE THREAD

**Issue by alanlivio** [TeleMidia/ginga#106]
gingagui faliing windows after update from mingw64/mingw-w64-x86_64-gdk-pixbuf2-2.36.11-1 to mingw64/mingw-w64-x86_64-gdk-pixbuf2-2.36.11-2

**Comment by alanlivio** [comment]
An workaround can be done by the commands:
```
wget http://repo.msys2.org/mingw/x86_64/mingw-w64-x86_64-gdk-pixbuf2-2.36.11-1-any.pkg.tar.xz
pacman -U mingw-w64-x86_64-gdk-pixbuf2-2.36.11-1-any.pkg.tar.xz
```
Then recompile and deploy ginga

**Comment by robertogerson** [comment]
Is this solution enough?  Or do we need a better solution for it?

**Comment by alanlivio** [comment]
This issue was reported by @jvgirard.
I think we need a better solution. 
I belive @Busson may take a look because he developed the gingagui.

**Comment by alanlivio** [comment]
@Busson  the precise error is depicted in the image bellow.
![screenshot 1](https://user-images.githubusercontent.com/604808/37117623-86aa214e-2230-11e8-835d-1e2570890643.png)

**Comment by alanlivio** [comment]
Done by commit 9c0492755289bf5340035db0d8752036d860dddb.
