### ISSUE TITLE
onSelection with link key param does not work when there is no assigned key

### ISSUE THREAD

**Issue by andrelbd1** [TeleMidia/ginga#107]
<causalConnector id="onSelectionStart">
        <connectorParam name="key"/>
        <simpleCondition role="onSelection" key="$key" />          
        <simpleAction role="start" max="unbounded" qualifier="seq"/>        
      </causalConnector>

      <link xconnector="conn#onSelectionStart">
        <bind component="empty3" role="onSelection"/>
        <bind component="fill3" role="start"/>
      </link>

**Comment by robertogerson** [comment]
Should this work?  Or should we through an error in the parser?

**Comment by alanlivio** [comment]
I think its should work. 
I believe that an <connectorParam> is optional do be configured by an <bindParam>.

**Comment by alanlivio** [comment]
This case was reported by @andrelbd1  at "jogo da velha" application

**Comment by robertogerson** [comment]
The commit eaf4389 implements this behavior.
