### ISSUE TITLE
src-gui/gingagui key events goes to both ginga and menu

### ISSUE THREAD

**Issue by alanlivio** [TeleMidia/ginga#116]

**Comment by Busson** [comment]
Done

**Comment by alanlivio** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [gingagui release](https://trello.com/c/AAOSfl3V/59-gingagui-release)

**Comment by alanlivio** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [gingagui release](https://trello.com/c/AAOSfl3V/59-gingagui-release)
