### ISSUE TITLE
Missing icons in gingagui after using installer

### ISSUE THREAD

**Issue by edcaraujo** [TeleMidia/ginga#141]
As shown below...

![ginga-missing-icons](https://user-images.githubusercontent.com/766807/39952818-66384530-5575-11e8-9878-f01aea94ba69.PNG)

**Comment by edcaraujo** [comment]
Forgot to say, i was using Window 10.

**Comment by alanlivio** [comment]
Thanks by the feedback @edcaraujo.
We add a new Windows installer[1], can you test it again?

[1] https://github.com/TeleMidia/ginga/releases
