### ISSUE TITLE
MacOS installation guide isn't working/updated

### ISSUE THREAD

**Issue by Ronkiro** [TeleMidia/ginga#182]
I'm not sure if we're supposed to support MacOS. Many of our collaborators tried it but they gave up and went to Windows/Linux through VM.
Maybe should we add a "deprecated" text to the document?

**Comment by Ronkiro** [comment]
Maybe it's just an update on the docs. I don't have a MacOS device to be sure

**Comment by alanlivio** [comment]
I update the README to highlight that is not stable the build.
