### ISSUE TITLE
Error when building for Ubuntu

### ISSUE THREAD

**Issue by Ronkiro** [TeleMidia/ginga#186]
All the installation worked alright, but it fails when trying to execute `ginga`

This is the error:
```
ginga: error while loading shared libraries: libnclua.so.0: cannot open shared object file: No such file or directory
```

I tried reinstalling nclua as the README.md said but it didn't work

**Comment by alanlivio** [comment]
Try to find the location of the libnclua.so at your machine and set its path to the LD_LIBRARY_PATH env varaible. Some ubu distribution use /usr/local/lib instead of /usr/lib (which does not need be added to the LD_LIBRARY_PATH ).

**Comment by Ronkiro** [comment]
I got some kernel errors on my VM so not managing to try the solution for now.
But i it's probably the correct solution, closing for now

**Comment by maktheus** [comment]
hi guys im with the same problem but im runnign on wsl... any solutions ?

**Comment by rafael2k** [comment]
Did you compile by hand both ginga and nclua?

**Comment by alanlivio** [comment]
Hi @maktheus. As I said, you may use a different place (maybe /usr/local/lib) for the nclua `.so` file. try to do a find and then add the path at your LD_LIBRARY_PATH.
