### ISSUE TITLE
Is doxygen in gihtub pages broken?

### ISSUE THREAD

**Issue by RodrigoDornelles** [TeleMidia/ginga#191]
analyzed the repository, I understood that there should be a page with documentation about it, but it doesn't seem like **gh-pages** is activated, as the URL is 404.

 * <https://telemedia.github.io/ginga>
 * <https://github.com/TeleMidia/ginga/blob/master/.github/workflows/gh-pages.yml>

Do you just need to activate it, or is it not ready yet? I can help with workflow and doxygen configuration if needed!

**Comment by alanlivio** [comment]
Thanks @RodrigoDornelles. I ran the workflow but indeed is not working. It was working in the past. Feel free to do a PR.

**Comment by RodrigoDornelles** [comment]
@alanlivio you must enable github pages in repository configuration and rerun the job.

**Comment by alanlivio** [comment]
Thanks @RodrigoDornelles. It is online now at https://telemidia.github.io/ginga
