### ISSUE TITLE
Implement lib/PlayerSigGen

### ISSUE THREAD

**Issue by alanlivio** [TeleMidia/ginga#70]
Implement a media player to generate audio signals.
It may enable create NCL applications that use audio watermarking in order to synchronize/communicate with other devices without networking (e.g. wifi).

NCL usage:
```
<media type="siggen">
  <property name="frequency" value="1800kz">
  <property name="amplitute value="0.5">
<media>
```

**Comment by alanlivio** [comment]
@jvgirard, is this issue done right?

**Comment by jvgirard** [comment]
Yes
