### ISSUE TITLE
Create unit test for zcmp

### ISSUE THREAD

**Issue by alanlivio** [TeleMidia/ginga#90]
![screenshot from 2018-02-06 14-50-10](https://user-images.githubusercontent.com/604808/35872112-1e63ade8-0b4d-11e8-94fc-1a19f2d66359.png)

**Comment by gflima** [comment]
Closed it because this is a file-static function.  There is no point in trying to test it.  You need to test the exported function that calls it.

**Comment by alanlivio** [comment]
OK. It's called in Formatter::redraw, which the issue for tests was defined in #92.
