### ISSUE TITLE
Capture gstreamer errors in lib/PlayerVideo

### ISSUE THREAD

**Issue by alanlivio** [TeleMidia/ginga#98]
When PlayerVideo have an error in gstreamer it make a fatal error to executable (see error bellow).
All code in libginga should capture errors and only report to the it's user (eg. ginga-cmd, ginga-gui, ginga-qt).
For instance, when this gstreamer have an error the ginga-gui die and the final user not know why.
In this case, PlayerVideo should capture the gstreamer error and inform error to ginga-gui, which will not die and show the problem to the user.

$ ./src/ginga.exe  -d examples/primeiro-joao/01sync.ncl
** (ginga.exe:8884): DEBUG: ginga::Formatter::setOptionDebug(): debug:=true
** (ginga.exe:8884): DEBUG: ginga::Formatter::setOptionExperimental(): experimental:=false
** (ginga.exe:8884): DEBUG: ginga::Formatter::setOptionOpenGL(): opengl:=false
** (ginga.exe:8884): DEBUG: ginga::Formatter::start(): examples/primeiro-joao/01sync.ncl
** (ginga.exe:8884): DEBUG: ginga::Context::afterTransition(): start __root__@lambda
** (ginga.exe:8884): DEBUG: ginga::Media::afterTransition(): start __settings__@lambda
** (ginga.exe:8884): DEBUG: ginga::PlayerVideo::start(): starting animation
** (ginga.exe:8884): DEBUG: ginga::Media::afterTransition(): start animation@lambda

** (ginga.exe:8884): WARNING **: ginga::PlayerVideo::cb_Bus(): No decoder available for type 'video/x-h264, stream-format=(string)byte-stream, alignment=(string)au, level=(string)3, profile=(string)high,
width=(int)640, height=(int)480, framerate=(fraction)30000/1001, pixel-aspect-ratio=(fraction)1/1, interlace-mode=(string)progressive, parsed=(boolean)true'.

** (ginga.exe:8884): ERROR **: ginga::PlayerVideo::cb_Bus(): Your GStreamer installation is missing a plug-in.

**Comment by robertogerson** [comment]
Do we need this issue in the "Refactoring Release" ?
